package com.openclassrooms.payMyBuddy.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="TransactionBetweenPersons")
public class TransactionBetweenPersons extends Transaction{

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "transactionReceivedList")
    private Person recipient;

    // Constructors needed (constructor with no argument, getters and setters are generated by lombok)

    public TransactionBetweenPersons(Person sender, float amount, Person recipient){
        this.setSender(sender);
        this.setAmount(amount);
        this.recipient=recipient;
    }

    public TransactionBetweenPersons(Person sender, float amount, Person recipient,String description){
        this.setSender(sender);
        this.setAmount(amount);
        this.setDescription(description);
        this.recipient=recipient;
    }

}
